export const START_LOADING = 'START_LOADING';
export const DONE_LOADING = 'DONE_LOADING';
export const FETCH_SLIDES = 'FETCH_SLIDES';
export const FETCH_STORIES = 'FETCH_STORIES';
export const UPDATE_SLIDES = 'UPDATE_SLIDES';
export const UPDATE_TODAY = 'UPDATE_TODAY';
